### ISSUE TITLE
Testnet issue

### ISSUE THREAD

**Issue by PavelMoneyin** [defund-labs/defund#21]
Whe i run validator and add all peers i can't run node. Looks like my node don't want to catch up peers. 

I am using following peers:
`peers = "f114c02efc5aa7ee3ee6733d806a1fae2fbfb66b@5.189.178.222:46656,b16142de5e7d89ee87f36d3bbdd2c2356ca2509a@75.119.155.248:26656,542cc6c360526930bcd0430934dff42265b77151@51.195.233.245:26656,08a6cdda6de67df616e996f2fe60590a5ad8402a@51.79.28.250:26656,599c0f5b1031b125b821c239056a1170a11c5255@141.95.101.46:26656,b74c7175157e90375933d6f5a7c573f565a69220@164.215.102.44:26656,fbffc68aeff7467dfe149fadaa12a7b721e99fe0@46.4.114.116:2665"`

And in my journal i have following issues.

```
INF Error reconnecting to peer. Trying again addr={"id":"b74c7175157e90375933d6f5a7c573f565a69220","ip":"164.215.102.44","port":26656} err="auth failure: secret conn failed: read tcp 154.12.244.137:58912->164.215.102.44:26656: i/o timeout" module=p2p tries=3
7:53AM INF Error reconnecting to peer. Trying again addr={"id":"b16142de5e7d89ee87f36d3bbdd2c2356ca2509a","ip":"75.119.155.248","port":26656} err="auth failure: secret conn failed: read tcp 154.12.244.137:60824->75.119.155.248:26656: i/o timeout" module=p2p tries=3
7:53AM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=0 numToDial=10
7:53AM INF Dialing peer address={"id":"2796e8756692aad9886a21c870afb3a4894696cb","ip":"89.163.164.207","port":26656} module=p2p
7:53AM INF Dialing peer address={"id":"fe2003178eac595207ec2ab8e817880bcc102444","ip":"188.34.188.244","port":26656} module=p2p
7:53AM INF Dialing peer address={"id":"228c010342d5d05295bea65670a3fbd5620fa383","ip":"141.95.101.90","port":26656} module=p2p
7:53AM INF Dialing peer address={"id":"8c6d4d571d795b7714408ddcfdf59c350ee081d2","ip":"85.10.216.151","port":26656} module=p2p
7:53AM INF Dialing peer address={"id":"b1aa571b79dadbf35aaac2b373948facc31b558b","ip":"141.95.109.238","port":26656} module=p2p
7:53AM INF Dialing peer address={"id":"88964516cf840e33c4b5806181aedb820e268409","ip":"45.77.75.4","port":26656} module=p2p
7:53AM INF Dialing peer address={"id":"d67ea8c379d6c354fad4c48c50bd356587549135","ip":"85.10.216.152","port":26656} module=p2p
7:53AM INF Dialing peer address={"id":"494b94431476a42972d4f64b7ccafd5ca023a084","ip":"164.68.103.100","port":26656} module=p2p
```

**Comment by schnetzlerjoe** [comment]
Hey! This is not a software issue so will be closing this but you will need to find an addrbook.json or find some peers/seeds from validator/node friends. It's up to validators to set the max limit of peers/seed connections. So you are connecting to validators who are full. I suggest pinging in the Discord or chat.

**Comment by PavelMoneyin** [comment]
> Hey! This is not a software issue so will be closing this but you will need to find an addrbook.json or find some peers/seeds from validator/node friends. It's up to validators to set the max limit of peers/seed connections. So you are connecting to validators who are full. I suggest pinging in the Discord or chat.

The problem was in peers. I take a peer, who shared it in discord and added it in my config.toml 

Maybe it will be good idea update address.book, genesis.json and peers in your documentation.
